project_id = "env(PROJECT_ID)"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 100

[auth]
site_url = "http://localhost:3001"
additional_redirect_urls = ["http://localhost:3001", "http://localhost:54321/auth/v1/callback"]
jwt_expiry = 36000

[db]
port = 54322

[studio]
port = 54323

# [auth.external.google]
# enabled = true
# client_id = "env(GOOGLE_CLIENT_ID)"
# secret = "env(GOOGLE_SECRET)"
# redirect_uri = "http://localhost:54321/auth/v1/callback"

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = true

[analytics]
enabled = true
port = 54327
vector_port = 54328
backend = "postgres"